apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: legal-compliance

resources:
  - namespace.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: legal-compliance-platform
  app.kubernetes.io/managed-by: kustomize
